name: Build Windows Exe

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Download FFmpeg for Windows
      # We download ffmpeg automatically so you don't have to upload it
      run: |
        curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
        7z x ffmpeg.zip
        move ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe .
        
    - name: Build EXE with PyInstaller
      run: |
        python -m PyInstaller --noconsole --clean --onefile --name "YT Downloader" --windowed --icon="icon.ico" --add-binary "ffmpeg.exe;." --collect-all customtkinter --collect-all yt_dlp --collect-all certifi --hidden-import=PIL --hidden-import=packaging --hidden-import=mutagen yt_downloader.py

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YT-Downloader-Windows
        path: dist/YT Downloader.exe
